from src.apps.school_management_system.teacher_management.models.teacher import Teacher
from src.apps.school_management_system.student_management.models.student import Student
from src.apps.school_management_system.contact_management.models.user_contact import UserContact
from src.apps.school_management_system.contact_management.models.school_contact import SchoolContact